export {
	CHUNK_OVERLAP,
	EMBEDDING_DIMENSIONS,
	EMBEDDING_MODEL,
	EMBEDDING_MODEL_ID,
	MAX_CHUNKS_PER_DOCUMENT,
	MAX_CONTEXT_CHUNKS,
	MAX_GRAPH_HOPS,
	OVERFETCH_MULTIPLIER,
	PARAGRAPH_CHUNK_TARGET,
	RRF_K,
	SECTION_CHUNK_TARGET,
} from '$lib/server/config';
