/**
 * Hosted-safe file excerpts, served from a BUILD-TIME SNAPSHOT.
 *
 * The hosted public endpoint is internet-facing and runs on Vercel, where the repository
 * source tree is NOT bundled into the serverless function — so reading files from disk at
 * runtime would fail in production. Instead, the registry-referenced public files are captured
 * into `mcp/public-excerpts.snapshot.json` at build time (regenerated by
 * `scripts/mcp/build-public-excerpts.ts`, drift-guarded by `mcp:excerpts:check`). That JSON is
 * imported statically here, so Vite inlines it into the server bundle: the exact same content
 * that ships to production is what tests read. No `fs`, no `process.cwd()`, no path traversal
 * surface at all — only exact-match lookup against the registry-derived allowlist. The snapshot
 * generator already excludes binary/oversize files, so only vetted text reaches this reader.
 */
import snapshotJson from '../../../../../mcp/public-excerpts.snapshot.json';
import type { NextAction, ToolDiag } from '../types';
import { EXCERPT_ALLOWLIST, isAllowlisted } from './allowlist';

export { EXCERPT_ALLOWLIST, isAllowlisted };

export const MAX_LINES = 250;
export const DEFAULT_LINES = 100;
const MAX_OUTPUT_BYTES = 36 * 1024;

interface ExcerptSnapshot {
	registryVersion: string;
	files: Record<string, string>;
}

const SNAPSHOT = snapshotJson as unknown as ExcerptSnapshot;
const SNAPSHOT_FILES: Record<string, string> = SNAPSHOT.files ?? {};

/** Paths actually present in the bundled snapshot (allowlisted files that were captured). */
export const SNAPSHOT_PATHS: ReadonlySet<string> = new Set(Object.keys(SNAPSHOT_FILES));

/**
 * A DISCRIMINATED union, not `{ ok: boolean }`, so the compiler forces a `diag` — and a `next`
 * recovery step — on every failure branch. The alternative — optional fields with `??` fallbacks
 * at the one call site that bridges to `errorResult` — would let a newly-added failure path
 * silently inherit the wrong reason, which is exactly the drift this channel exists to prevent.
 */
export type ExcerptResult =
	| { ok: true; text: string }
	| { ok: false; text: string; diag: ToolDiag; next: readonly NextAction[] };

export function readAllowlistedExcerpt(path: string, startLine = 1, lineCount = DEFAULT_LINES): ExcerptResult {
	if (typeof path !== 'string' || path.trim().length === 0) {
		return {
			ok: false,
			text: 'path must be a non-empty repo-relative string.',
			diag: 'invalid_args',
			next: [{ tool: 'get_pattern', why: 'pattern cards list the repo-relative paths this tool can read.' }],
		};
	}
	if (path.startsWith('/')) {
		return {
			ok: false,
			text: `absolute paths are rejected — pass a repo-relative path (got '${path}').`,
			diag: 'invalid_args',
			next: [{ tool: 'get_pattern', why: 'pattern cards list the repo-relative paths this tool can read.' }],
		};
	}
	if (!isAllowlisted(path)) {
		return {
			ok: false,
			text: `'${path}' is not an allowlisted file. The hosted endpoint only excerpts files referenced by the pattern registry — use a path from get_pattern / trace_capability output.`,
			diag: 'not_found',
			next: [
				{ tool: 'trace_capability', why: 'trace the capability to find which registry files cover it.' },
				{ tool: 'get_pattern', why: 'the full card lists every readable code entry point.' },
			],
		};
	}
	const content = SNAPSHOT_FILES[path];
	if (content === undefined) {
		// OPERATOR alarm, not a caller error: the registry references this file but the build-time
		// snapshot does not carry it, so `mcp:excerpts:build` drifted. A non-zero count of these in
		// production means the deployed snapshot is stale.
		return {
			ok: false,
			text: `'${path}' is allowlisted but not present in the deployment snapshot — regenerate it with mcp:excerpts:build.`,
			diag: 'snapshot_miss',
			next: [
				{ tool: 'search_patterns', why: 'other patterns cover adjacent code while this snapshot entry is stale.' },
			],
		};
	}
	const lines = content.split('\n');
	const total = lines.length;
	const from = Math.max(1, Math.floor(startLine));
	if (from > total) {
		return {
			ok: false,
			text: `start_line ${from} is beyond EOF — '${path}' has ${total} lines.`,
			diag: 'invalid_args',
			next: [{ tool: 'get_file_excerpt', args: { start_line: 1 }, why: 'retry from line 1 with the same path.' }],
		};
	}
	const count = Math.min(Math.max(1, Math.floor(lineCount)), MAX_LINES);
	const to = Math.min(from + count - 1, total);
	const width = String(to).length;
	const body = lines
		.slice(from - 1, to)
		.map((line, index) => `${String(from + index).padStart(width)}\t${line}`)
		.join('\n');
	let text = `# ${path} (lines ${from}-${to} of ${total})\n${body}`;
	if (text.length > MAX_OUTPUT_BYTES) {
		text = `${text.slice(0, MAX_OUTPUT_BYTES)}\n… [truncated at ${MAX_OUTPUT_BYTES} bytes — request a narrower range]`;
	}
	return { ok: true, text };
}
